resolver:
  scope-order:
    - local

local-services:
  start-dirsvc: true
  start-qpm: true
  dirsvc:
    name: qfw-local-dirsvc
    bind-host: 127.0.0.1
    port: auto
  service-manifest: <prefix>/share/qfw/config/services/qfw_services.yaml
