install-profile: container
runtime-mode: container
mpi-transport-mode: auto
base-dir: /workspace/qfw-container-base
python-venv-activate: /workspace/qfw-container-base/venv/bin/activate
libfabric-install: /opt/qfw/libfabric
mpi-install: /opt/qfw/openmpi
dev-install: /workspace/qfw-container-base/rocm
build-dependencies: False
qfw-dep-build-version: 20260311-150318
