base-dir: /sw/frontier/qhpc
runtime-mode: frontier
python-venv-activate: /ccs/home/shehataa/tmp/qfw_venv/bin/activate
libfabric-install: /sw/frontier/ums/ums024/cce/18.0.1/install/libfabric-2.3.1-20251111.dbg
mpi-install: /sw/frontier/ums/ums024/cce/18.0.1/install/openmpi-5.0.9-20251111.dbg
dev-install: /opt/rocm-6.2.4/
openblas-root: /sw/frontier/spack-envs/core-25.03/opt/gcc-13.2/openblas-0.3.28-33iixip2ibzkhghihg6f7euobyeosjje
cmake-root: /sw/frontier/spack-envs/core-25.03/opt/gcc-13.2/cmake-3.30.5-3megaha56irdlal5or2bjkasn2zj5fvp
gcc-root: /opt/cray/pe/gcc/12.2.0/
build-dependencies: True
